services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - PORT=8000
      - DB_URL=postgresql+asyncpg://postgres:134679@db:5432/catalogo_livros
      - JWT_SECRET=_PjYCgkedWPSDbNYFkSbS7lQ6hR1ApgXccZFQ2l83Bs
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER=/usr/bin/chromedriver
    depends_on:
      - db

  init_db:
    build: .
    environment:
      - APP_ENV=development
      - DB_URL=postgresql+asyncpg://postgres:134679@db:5432/catalogo_livros
      - JWT_SECRET=_PjYCgkedWPSDbNYFkSbS7lQ6hR1ApgXccZFQ2l83Bs
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER=/usr/bin/chromedriver
    depends_on:
      - db
    command: ["python", "criar_tabelas.py"]

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=catalogo_livros
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=134679
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: